---

# Pyup configuration

branch: 'develop'
requirements:
  - 'requirements.txt':
      updates: 'all'
      pin: True
  - 'ansible-role-{{ cookiecutter.ansible_role_name }}/requirements.txt':
      updates: 'all'
      pin: True
